/**
 * Import Cline hook scripts from `.cline/hooks/` into canonical hooks.yaml.
 *
 * Project scope resolves this against the project root; global scope
 * resolves the identical relative path against `$HOME` (CLI docs:
 * `~/.cline/hooks`) — a single read covers both.
 *
 * Scripts are generated by agentsmesh and embed metadata as comments:
 *   # agentsmesh-event:   <canonical event name>
 *   # agentsmesh-matcher: <matcher pattern>
 *   # agentsmesh-command: <shell command>
 */

import { AB_HOOKS } from '../../core/canonical-paths.js';
import { join, basename, dirname } from 'node:path';
import { stringify as yamlStringify } from 'yaml';
import type { ImportResult } from '../../core/types.js';
import {
  readDirRecursiveNoSymlinks,
  readFileSafe,
  writeFileAtomic,
  mkdirp,
} from '../../utils/filesystem/fs.js';
import { CLINE_TARGET, CLINE_HOOKS_DIR } from './constants.js';

function extractMeta(content: string, key: string): string | null {
  const match = content.match(new RegExp(`^# agentsmesh-${key}:\\s*(.+)$`, 'm'));
  return match?.[1]?.trim() ?? null;
}

async function loadHooksFromDir(
  dir: string,
  hooks: Record<string, Array<{ matcher: string; command: string }>>,
): Promise<void> {
  const files = await readDirRecursiveNoSymlinks(dir).catch(() => []);
  const shFiles = files.filter((f) => basename(f).endsWith('.sh') && dirname(f) === dir);
  for (const srcPath of shFiles) {
    const content = await readFileSafe(srcPath);
    if (!content) continue;
    const event = extractMeta(content, 'event');
    const command = extractMeta(content, 'command');
    if (!event || !command) continue;
    const matcher = extractMeta(content, 'matcher') ?? '*';
    if (!hooks[event]) hooks[event] = [];
    hooks[event]!.push({ matcher, command });
  }
}

/**
 * Import Cline hook scripts into canonical hooks.yaml.
 *
 * @param projectRoot - Project root directory (or homedir() for global mode)
 * @param results - Import results accumulator
 */
export async function importClineHooks(
  projectRoot: string,
  results: ImportResult[],
): Promise<void> {
  const hooks: Record<string, Array<{ matcher: string; command: string }>> = {};

  const hooksDir = join(projectRoot, CLINE_HOOKS_DIR);
  await loadHooksFromDir(hooksDir, hooks);

  if (Object.keys(hooks).length === 0) return;

  const destPath = join(projectRoot, AB_HOOKS);
  await mkdirp(dirname(destPath));
  await writeFileAtomic(destPath, yamlStringify(hooks));
  results.push({
    fromTool: CLINE_TARGET,
    fromPath: hooksDir,
    toPath: AB_HOOKS,
    feature: 'hooks',
  });
}
