/**
 * The MCP registry manifest must stay publishable.
 *
 * The registry proves npm ownership by reading `mcpName` out of the *published*
 * package.json and requiring it to equal the server name in `server.json`
 * (docs/modelcontextprotocol-io/package-types.mdx in modelcontextprotocol/registry).
 * The field was missing, so a submission would have been rejected — and because
 * the check reads the published tarball, the fix only takes effect in a release.
 *
 * The version is the other trap. `server.json` used to carry a hand-maintained
 * copy of package.json's version, which goes stale the moment changesets bumps
 * it, and nothing referenced the file so nothing noticed. The package-level copy
 * is gone (the schema makes it optional, so npm resolution stays current on its
 * own) and the server-level copy is generated by `scripts/sync-release-versions.ts`
 * during `changeset version`.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { syncVersion } from '../../../scripts/sync-release-versions-core.js';

const ROOT = process.cwd();

const packageJson = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')) as {
  name: string;
  version: string;
  mcpName?: string;
  scripts: Record<string, string>;
};

const manifestText = readFileSync(join(ROOT, 'server.json'), 'utf8');
const manifest = JSON.parse(manifestText) as {
  name: string;
  version: string;
  packages: Record<string, unknown>[];
};

describe('npm ownership verification', () => {
  it('declares mcpName, without which the registry rejects the submission', () => {
    expect(packageJson.mcpName).toBe(manifest.name);
  });

  it('namespaces the server under the GitHub owner, lowercased as the registry requires', () => {
    expect(manifest.name).toMatch(/^io\.github\.[a-z0-9-]+\/[a-z0-9-]+$/);
    expect(manifest.name.endsWith(`/${packageJson.name}`)).toBe(true);
  });

  it('advertises the npm package this repository publishes', () => {
    expect(manifest.packages).toHaveLength(1);
    expect(manifest.packages[0]!.registryType).toBe('npm');
    expect(manifest.packages[0]!.identifier).toBe(packageJson.name);
  });
});

describe('version drift', () => {
  it('pins no package version, so npm resolution cannot go stale', () => {
    expect(Object.keys(manifest.packages[0]!)).toEqual([
      'registryType',
      'registryBaseUrl',
      'identifier',
      'transport',
      'packageArguments',
    ]);
  });

  it('carries the version changesets generated', () => {
    expect(manifest.version).toBe(packageJson.version);
  });

  it('rewrites the server version and nothing else', () => {
    const next = JSON.parse(syncVersion(manifestText, '9.9.9')) as Record<string, unknown>;
    expect(next.version).toBe('9.9.9');
    expect({ ...next, version: manifest.version }).toEqual(JSON.parse(manifestText));
  });

  it('leaves the committed manifest byte-identical when already in sync', () => {
    expect(syncVersion(manifestText, packageJson.version)).toBe(manifestText);
  });
});

describe('release wiring', () => {
  it('runs the sync as part of changeset version', () => {
    expect(packageJson.scripts.version).toBe(
      'changeset version && tsx scripts/sync-release-versions.ts',
    );
  });

  it('points changesets at that script, or the sync would never run', () => {
    // changesets/action@v1 defaults to a bare `changeset version`, which skips
    // the npm script entirely.
    const workflow = readFileSync(join(ROOT, '.github/workflows/publish.yml'), 'utf8');
    expect(workflow).toContain('version: pnpm run version');
  });
});
