import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { graphFilePath } from '../../../src/lessons/graph-store.js';
import { isOlderVersion } from '../../../src/lessons/hook-notices.js';
import { graphOf, useHookProject } from './hook-test-helpers.js';

const RULE = 'Source rule.';
const project = useHookProject(() =>
  graphOf({ s: { rule: RULE, trigger: { kind: 'file_glob', pattern: 'src/**' } } }),
);

const run = project.recall;
const edit = (session?: string): Record<string, unknown> => ({
  ...(session !== undefined ? { session_id: session } : {}),
  hook_event_name: 'PreToolUse',
  tool_input: { file_path: 'src/x.ts' },
});

function writeGraphText(text: string): void {
  writeFileSync(graphFilePath(project.root()), text, 'utf8');
}

function writeLock(libVersion: string): void {
  writeFileSync(
    join(project.root(), '.agentsmesh', '.lock'),
    `generated_at: "2026-09-01T00:00:00Z"\ngenerated_by: test\nlib_version: ${libVersion}\nchecksums: {}\n`,
    'utf8',
  );
}

describe('hook warns when the lessons graph cannot be read', () => {
  it('names a git merge conflict when the graph holds conflict markers', async () => {
    writeGraphText('<<<<<<< HEAD\n{"version":2}\n=======\n{"version":2}\n>>>>>>> theirs\n');
    const ctx = await run(edit(project.session('conflict')));
    expect(ctx).toContain('.agentsmesh/lessons/lessons.json');
    expect(ctx).toContain('merge conflict');
    expect(ctx).toContain('lesson recall is off');
    expect(ctx).toContain('lessons validate');
  });

  it('calls a non-conflict parse failure corrupt', async () => {
    writeGraphText('{ not json');
    const ctx = await run(edit(project.session('corrupt')));
    expect(ctx).toContain('corrupt');
    expect(ctx).not.toContain('merge conflict');
    expect(ctx).toContain('lesson recall is off');
  });

  it('asks for an upgrade when the graph was written by a newer schema', async () => {
    writeGraphText(JSON.stringify({ version: 99, lessons: {}, topics: {}, triggers: {} }));
    const ctx = await run(edit(project.session('newer')));
    expect(ctx).toContain('version 99');
    expect(ctx).toContain('Upgrade agentsmesh');
  });

  it('warns at most once per session', async () => {
    writeGraphText('{ not json');
    const s = project.session('once');
    expect(await run(edit(s))).toContain('corrupt');
    expect(await run(edit(s))).toBe('');
  });

  it('also warns on UserPromptSubmit', async () => {
    writeGraphText('{ not json');
    const prompt = {
      session_id: project.session('prompt'),
      hook_event_name: 'UserPromptSubmit',
      prompt: 'fix the bug',
    };
    expect(await run(prompt)).toContain('lesson recall is off');
  });

  it('stays silent for a healthy graph', async () => {
    const ctx = await run(edit(project.session('healthy')));
    expect(ctx).toContain(RULE);
    expect(ctx).not.toContain('recall is off');
  });
});

describe('hook warns when the installed agentsmesh is older than the project', () => {
  it('injects a one-time warning naming both versions', async () => {
    writeLock('999.0.0');
    const s = project.session('skew');
    const first = await run(edit(s));
    expect(first).toContain('999.0.0');
    expect(first).toContain('older');
    expect(first).toContain(RULE);
    expect(await run(edit(s))).toBe('');
  });

  it('stays silent when the project was generated by an older or equal version', async () => {
    writeLock('0.0.1');
    expect(await run(edit(project.session('ok')))).not.toContain('older');
  });

  it('stays silent when the lock version is not a version', async () => {
    writeLock('"not-a-version"');
    expect(await run(edit(project.session('junk')))).not.toContain('older');
  });

  it('warns even when the action itself matches no lesson', async () => {
    writeLock('999.0.0');
    const ls = { session_id: project.session('skew-nomatch'), tool_input: { command: 'ls -la' } };
    expect(await run(ls)).toContain('older');
  });
});

describe('isOlderVersion', () => {
  it('orders by major, minor, then patch numerically', () => {
    expect(isOlderVersion('0.40.0', '0.9.0')).toBe(false);
    expect(isOlderVersion('0.9.0', '0.40.0')).toBe(true);
    expect(isOlderVersion('1.2.3', '1.10.0')).toBe(true);
    expect(isOlderVersion('2.0.0', '2.0.0')).toBe(false);
  });

  it('accepts a leading v and ignores build metadata', () => {
    expect(isOlderVersion('v1.2.3', '1.2.3+build.7')).toBe(false);
    expect(isOlderVersion('1.2.3+build.7', 'v1.2.3')).toBe(false);
    expect(isOlderVersion('v1.2.2', '1.2.3+build.7')).toBe(true);
  });

  it('ranks a prerelease below its release', () => {
    expect(isOlderVersion('1.0.0-beta.1', '1.0.0')).toBe(true);
    expect(isOlderVersion('1.0.0', '1.0.0-rc.1')).toBe(false);
  });

  it('is false when either side is not a version', () => {
    expect(isOlderVersion('unknown', '1.0.0')).toBe(false);
    expect(isOlderVersion('1.0.0', '')).toBe(false);
    expect(isOlderVersion('1.0', '2.0.0')).toBe(false);
    expect(isOlderVersion('1.2.3.4', '2.0.0')).toBe(false);
  });
});
