import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
export { expectedRefs, outputPaths, type TargetName } from './reference-targets.js';

export function appendGenerateReferenceMatrix(dir: string): void {
  const abs = (...parts: string[]): string => join(dir, ...parts);
  mkdirSync(abs('docs'), { recursive: true });
  writeFileSync(abs('docs', 'some-doc.md'), '# Some Doc\n');
  writeFileSync(abs('docs', 'agents-folder-structure-research.md'), '# Structure Research\n');

  writeFileSync(
    abs('.agentsmesh', 'rules', '_root.md'),
    `${readFileSync(abs('.agentsmesh', 'rules', '_root.md'), 'utf-8').trim()}\n\n## Rewrite Matrix\nPlain: .agentsmesh/rules/typescript.md, .agentsmesh/commands/review.md, .agentsmesh/agents/code-reviewer.md, .agentsmesh/skills/api-generator/SKILL.md, .agentsmesh/skills/api-generator/template.ts, .agentsmesh/skills/api-generator/references/route-checklist.md.\nMarkdown: [.agentsmesh/rules/typescript.md](.agentsmesh/rules/typescript.md), [.agentsmesh/skills/api-generator/references/route-checklist.md](.agentsmesh/skills/api-generator/references/route-checklist.md).\nStructured: @.agentsmesh/commands/review.md, ".agentsmesh/agents/code-reviewer.md", (.agentsmesh/skills/api-generator/SKILL.md), <.agentsmesh/skills/api-generator/template.ts>.\nDirectories: .agentsmesh/skills/api-generator/references and .agentsmesh/skills/api-generator/references/.\nProse dirs (no rewrite): scripts/ docs/ references/.\nStatus markers: ✓ / ✗.\nExternal refs: git@github.com:owner/repo.git, ssh://git@github.com/owner/repo.git, mailto:test@example.com, vscode://file/path.\nWindows relative: ..\\commands\\review.md, ..\\agents\\code-reviewer.md, ..\\skills\\api-generator\\SKILL.md, ..\\skills\\api-generator\\template.ts, ..\\skills\\api-generator\\references\\route-checklist.md, ..\\..\\docs\\some-doc.md.\nMixed separators: .agentsmesh\\commands/review.md, .agentsmesh\\skills/api-generator\\references/route-checklist.md.\nRelative: .agentsmesh/rules/typescript.md, .agentsmesh/commands/review.md, .agentsmesh/agents/code-reviewer.md, .agentsmesh/skills/api-generator/SKILL.md, .agentsmesh/skills/api-generator/template.ts, .agentsmesh/skills/api-generator/references/route-checklist.md, ../../docs/some-doc.md.\nOvertravel: ../../../../docs/agents-folder-structure-research.md.\nAbsolute: ${abs('.agentsmesh', 'rules', 'typescript.md')}, ${abs('.agentsmesh', 'commands', 'review.md')}, ${abs('.agentsmesh', 'skills', 'api-generator', 'references', 'route-checklist.md')}\nLine ref: .agentsmesh/rules/typescript.md:42.\nProtocol-relative: //cdn.example.com/lib.js.\nInline code: \`../../docs/some-doc.md\`.\nCode block:\n\`\`\`\n../../docs/some-doc.md\n\`\`\`\nTilde block:\n~~~\n../../docs/some-doc.md\n~~~\n`,
  );
  writeFileSync(
    abs('.agentsmesh', 'rules', 'typescript.md'),
    `${readFileSync(abs('.agentsmesh', 'rules', 'typescript.md'), 'utf-8').trim()}\n\n## Rewrite Matrix\nPlain: .agentsmesh/rules/_root.md, .agentsmesh/commands/review.md, .agentsmesh/agents/code-reviewer.md, .agentsmesh/skills/api-generator/SKILL.md, .agentsmesh/skills/api-generator/template.ts, .agentsmesh/skills/api-generator/references/route-checklist.md.\nMarkdown: [.agentsmesh/rules/_root.md](.agentsmesh/rules/_root.md), [.agentsmesh/commands/review.md](.agentsmesh/commands/review.md).\nStructured: @.agentsmesh/agents/code-reviewer.md, ".agentsmesh/skills/api-generator/SKILL.md", (.agentsmesh/skills/api-generator/references/route-checklist.md), <.agentsmesh/skills/api-generator/template.ts>.\nDirectories: .agentsmesh/skills/api-generator/references and .agentsmesh/skills/api-generator/references/.\nProse dirs (no rewrite): scripts/ docs/ references/.\nStatus markers: ✓ / ✗.\nWindows relative: ..\\commands\\review.md, ..\\agents\\code-reviewer.md, ..\\skills\\api-generator\\SKILL.md, ..\\skills\\api-generator\\template.ts, ..\\skills\\api-generator\\references\\route-checklist.md, ..\\..\\docs\\some-doc.md.\nMixed separators: .agentsmesh\\commands/review.md, .agentsmesh\\skills/api-generator\\references/route-checklist.md.\nRelative: .agentsmesh/rules/_root.md, .agentsmesh/commands/review.md, .agentsmesh/agents/code-reviewer.md, .agentsmesh/skills/api-generator/SKILL.md, .agentsmesh/skills/api-generator/template.ts, .agentsmesh/skills/api-generator/references/route-checklist.md, ../../docs/some-doc.md.\nOvertravel: ../../../../docs/agents-folder-structure-research.md.\nAbsolute: ${abs('.agentsmesh', 'rules', '_root.md')}, ${abs('.agentsmesh', 'commands', 'review.md')}, ${abs('.agentsmesh', 'skills', 'api-generator', 'references', 'route-checklist.md')}\n`,
  );
  writeFileSync(
    abs('.agentsmesh', 'commands', 'review.md'),
    `${readFileSync(abs('.agentsmesh', 'commands', 'review.md'), 'utf-8').trim()}\n\nPlain: .agentsmesh/rules/typescript.md, .agentsmesh/rules/_root.md, .agentsmesh/skills/api-generator/SKILL.md, .agentsmesh/skills/api-generator/template.ts, .agentsmesh/skills/api-generator/references/route-checklist.md.\nMarkdown: [.agentsmesh/rules/typescript.md](.agentsmesh/rules/typescript.md), [.agentsmesh/skills/api-generator/template.ts](.agentsmesh/skills/api-generator/template.ts).\nStructured: @.agentsmesh/rules/_root.md, ".agentsmesh/skills/api-generator/SKILL.md", (.agentsmesh/skills/api-generator/references/route-checklist.md), <.agentsmesh/skills/api-generator/template.ts>.\nDirectories: .agentsmesh/skills/api-generator/references and .agentsmesh/skills/api-generator/references/.\nStatus markers: ✓ / ✗.\nWindows relative: ..\\rules\\typescript.md, ..\\rules\\_root.md, ..\\skills\\api-generator\\SKILL.md, ..\\skills\\api-generator\\template.ts, ..\\skills\\api-generator\\references\\route-checklist.md, ..\\..\\docs\\some-doc.md.\nMixed separators: .agentsmesh\\rules/typescript.md, .agentsmesh\\skills/api-generator\\template.ts.\nRelative: .agentsmesh/rules/typescript.md, .agentsmesh/rules/_root.md, .agentsmesh/skills/api-generator/SKILL.md, .agentsmesh/skills/api-generator/template.ts, .agentsmesh/skills/api-generator/references/route-checklist.md, ../../docs/some-doc.md.\nOvertravel: ../../../../docs/agents-folder-structure-research.md.\nAbsolute: ${abs('.agentsmesh', 'rules', 'typescript.md')}, ${abs('.agentsmesh', 'skills', 'api-generator', 'template.ts')}\n`,
  );
  writeFileSync(
    abs('.agentsmesh', 'agents', 'code-reviewer.md'),
    `${readFileSync(abs('.agentsmesh', 'agents', 'code-reviewer.md'), 'utf-8').trim()}\n\nPlain: .agentsmesh/commands/review.md, .agentsmesh/rules/typescript.md, .agentsmesh/skills/api-generator/SKILL.md, .agentsmesh/skills/api-generator/template.ts.\nMarkdown: [.agentsmesh/commands/review.md](.agentsmesh/commands/review.md), [.agentsmesh/rules/typescript.md](.agentsmesh/rules/typescript.md).\nStructured: @.agentsmesh/commands/review.md, ".agentsmesh/skills/api-generator/SKILL.md", (.agentsmesh/skills/api-generator/template.ts), <.agentsmesh/skills/api-generator/references/route-checklist.md>.\nStatus markers: ✓ / ✗.\nWindows relative: ..\\commands\\review.md, ..\\rules\\typescript.md, ..\\skills\\api-generator\\SKILL.md, ..\\skills\\api-generator\\template.ts, ..\\skills\\api-generator\\references\\route-checklist.md, ..\\..\\docs\\some-doc.md.\nMixed separators: .agentsmesh\\commands/review.md, .agentsmesh\\skills/api-generator\\template.ts.\nRelative: .agentsmesh/commands/review.md, .agentsmesh/rules/typescript.md, .agentsmesh/skills/api-generator/SKILL.md, .agentsmesh/skills/api-generator/template.ts, .agentsmesh/skills/api-generator/references/route-checklist.md, ../../docs/some-doc.md.\nOvertravel: ../../../../docs/agents-folder-structure-research.md.\nAbsolute: ${abs('.agentsmesh', 'commands', 'review.md')}, ${abs('.agentsmesh', 'skills', 'api-generator', 'template.ts')}\n`,
  );
  writeFileSync(
    abs('.agentsmesh', 'skills', 'api-generator', 'SKILL.md'),
    `${readFileSync(abs('.agentsmesh', 'skills', 'api-generator', 'SKILL.md'), 'utf-8').trim()}\n\nPlain: .agentsmesh/rules/typescript.md, .agentsmesh/rules/_root.md, .agentsmesh/commands/review.md, .agentsmesh/agents/code-reviewer.md, .agentsmesh/skills/api-generator/template.ts, .agentsmesh/skills/api-generator/references/route-checklist.md.\nMarkdown: [.agentsmesh/rules/typescript.md](.agentsmesh/rules/typescript.md), [.agentsmesh/commands/review.md](.agentsmesh/commands/review.md).\nStructured: @.agentsmesh/rules/_root.md, ".agentsmesh/agents/code-reviewer.md", (.agentsmesh/skills/api-generator/references/route-checklist.md), <.agentsmesh/skills/api-generator/template.ts>.\nDirectories: .agentsmesh/skills/api-generator/references and .agentsmesh/skills/api-generator/references/.\nStatus markers: ✓ / ✗.\nWindows relative: ..\\..\\rules\\typescript.md, ..\\..\\rules\\_root.md, ..\\..\\commands\\review.md, ..\\..\\agents\\code-reviewer.md, template.ts, references\\route-checklist.md, ..\\..\\..\\docs\\some-doc.md.\nMixed separators: .agentsmesh\\rules/typescript.md, .agentsmesh\\skills/api-generator\\references/route-checklist.md.\nRelative: .agentsmesh/rules/typescript.md, .agentsmesh/rules/_root.md, .agentsmesh/commands/review.md, .agentsmesh/agents/code-reviewer.md, .agentsmesh/skills/api-generator/template.ts, .agentsmesh/skills/api-generator/references/route-checklist.md, ../../../docs/some-doc.md.\nOvertravel: ../../../../docs/agents-folder-structure-research.md.\nAbsolute: ${abs('.agentsmesh', 'rules', 'typescript.md')}, ${abs('.agentsmesh', 'commands', 'review.md')}, ${abs('.agentsmesh', 'skills', 'api-generator', 'references', 'route-checklist.md')}\n`,
  );
  writeFileSync(
    abs('.agentsmesh', 'skills', 'api-generator', 'template.ts'),
    `${readFileSync(abs('.agentsmesh', 'skills', 'api-generator', 'template.ts'), 'utf-8').trim()}\n// Plain: .agentsmesh/rules/typescript.md, .agentsmesh/commands/review.md, .agentsmesh/agents/code-reviewer.md, .agentsmesh/skills/api-generator/SKILL.md, .agentsmesh/skills/api-generator/references/route-checklist.md\n// Markdown: [.agentsmesh/commands/review.md](.agentsmesh/commands/review.md), [.agentsmesh/skills/api-generator/references/route-checklist.md](.agentsmesh/skills/api-generator/references/route-checklist.md)\n// Structured: @.agentsmesh/rules/_root.md, ".agentsmesh/commands/review.md", (SKILL.md), <references/route-checklist.md>\n// Directories: references and references/\n// Status markers: ✓ / ✗\n// Windows relative: ..\\..\\rules\\typescript.md, ..\\..\\commands\\review.md, ..\\..\\agents\\code-reviewer.md, SKILL.md, references\\route-checklist.md, ..\\..\\..\\docs\\some-doc.md\n// Mixed separators: .agentsmesh\\commands/review.md, .agentsmesh\\skills/api-generator\\references/route-checklist.md\n// Relative: .agentsmesh/rules/typescript.md, .agentsmesh/commands/review.md, .agentsmesh/agents/code-reviewer.md, SKILL.md, references/route-checklist.md, ../../../docs/some-doc.md\n// Overtravel: ../../../../docs/agents-folder-structure-research.md\n// Absolute: ${abs('.agentsmesh', 'rules', 'typescript.md')}, ${abs('.agentsmesh', 'commands', 'review.md')}, ${abs('.agentsmesh', 'skills', 'api-generator', 'SKILL.md')}, ${abs('.agentsmesh', 'skills', 'api-generator', 'references', 'route-checklist.md')}\n`,
  );
}
