/**
 * Junie global-scope config emitters.
 *
 * Handles two distinct global config files:
 *
 *   - `~/.junie/allowlist.json` — action allowlist (permissions). Generated by
 *     `generatePermissions` only at global scope; the real schema requires
 *     `rules` to be a categorized object (fileEditing / executables / mcpTools /
 *     readOutsideProject), NOT a flat array. Documented at:
 *     https://junie.jetbrains.com/docs/action-allowlist-junie-cli.html
 *
 *   - `~/.junie/config.json` — multi-feature config (model, provider, brave,
 *     mcp-locations, hooks, etc.). `emitJunieScopedSettings` folds hooks into
 *     this file at global scope. `mergeJunieConfig` preserves pre-existing keys
 *     when regenerating. Documented at:
 *     https://junie.jetbrains.com/docs/junie-cli-configuration.html
 */

import type { FeatureGeneratorOutput } from '../catalog/target.interface.js';
import type { CanonicalFiles } from '../../core/types.js';
import type { GenerateFeatureContext } from '../catalog/target.interface.js';
import type { TargetLayoutScope } from '../catalog/target-descriptor.js';
import { JUNIE_GLOBAL_ALLOWLIST, JUNIE_GLOBAL_CONFIG } from './constants.js';

export type JunieOutput = FeatureGeneratorOutput;

/**
 * Convert a tool/path name to a Junie allowlist rule entry.
 *
 * Junie uses `pattern` for glob-syntax entries and `prefix` for literal
 * prefix matches. The only valid `action` values are "allow" and "ask" —
 * Junie has no "deny" action, so deny entries are mapped to "ask" (requires
 * explicit user approval) as the closest safe equivalent.
 */
function toAllowlistEntry(
  name: string,
  behavior: 'allow' | 'deny' | 'ask',
): { prefix?: string; pattern?: string; action: 'allow' | 'ask' } {
  const action: 'allow' | 'ask' = behavior === 'allow' ? 'allow' : 'ask';
  if (name.includes('*') || name.includes('?') || name.includes('[')) {
    return { pattern: name, action };
  }
  return { prefix: name, action };
}

/**
 * Generate `~/.junie/allowlist.json` (global scope only).
 *
 * Canonical allow/deny/ask entries are mapped to the `executables` category
 * (the most general one) since the canonical permissions model does not
 * distinguish file-editing vs. executable vs. MCP tool contexts.
 */
export function generatePermissions(
  canonical: CanonicalFiles,
  ctx?: GenerateFeatureContext,
): JunieOutput[] {
  if (ctx?.scope !== 'global') return [];
  if (!canonical.permissions) return [];
  const { allow, deny } = canonical.permissions;
  const ask = canonical.permissions.ask ?? [];
  if (allow.length === 0 && deny.length === 0 && ask.length === 0) return [];

  const executableRules: Array<{ prefix?: string; pattern?: string; action: 'allow' | 'ask' }> = [
    ...allow.map((name) => toAllowlistEntry(name, 'allow')),
    ...deny.map((name) => toAllowlistEntry(name, 'deny')),
    ...ask.map((name) => toAllowlistEntry(name, 'ask')),
  ];

  const payload = {
    defaultBehavior: 'ask',
    allowReadonlyCommands: true,
    rules: {
      fileEditing: { rules: [] as unknown[] },
      executables: { rules: executableRules },
      mcpTools: { rules: [] as unknown[] },
      readOutsideProject: { rules: [] as unknown[] },
    },
  };

  return [{ path: JUNIE_GLOBAL_ALLOWLIST, content: JSON.stringify(payload, null, 2) }];
}

/**
 * Fold hooks into `~/.junie/config.json` at global scope.
 *
 * Called via `descriptor.emitScopedSettings` — gated by the `enabledFeatures`
 * set so a disabled `hooks` feature never leaks into the config file.
 */
export function emitJunieScopedSettings(
  canonical: CanonicalFiles,
  scope: TargetLayoutScope,
  enabledFeatures: ReadonlySet<string>,
): readonly { readonly path: string; readonly content: string }[] {
  if (scope !== 'global') return [];

  const config: Record<string, unknown> = {};

  if (enabledFeatures.has('hooks') && canonical.hooks) {
    const hooksOut: Record<string, unknown[]> = {};
    for (const [event, entries] of Object.entries(canonical.hooks)) {
      if (!entries || entries.length === 0) continue;
      hooksOut[event] = entries.map((entry) => ({
        matcher: entry.matcher,
        hooks: [
          {
            type: 'command',
            command: entry.command,
            ...(entry.timeout !== undefined ? { timeout: entry.timeout } : {}),
          },
        ],
      }));
    }
    if (Object.keys(hooksOut).length > 0) {
      config.hooks = hooksOut;
    }
  }

  return Object.keys(config).length === 0
    ? []
    : [{ path: JUNIE_GLOBAL_CONFIG, content: JSON.stringify(config, null, 2) }];
}

/**
 * Merge a newly generated `~/.junie/config.json` into the existing file,
 * preserving keys written by other passes (e.g. mcp-locations, brave, model).
 */
export function mergeJunieConfig(existing: string | null, newContent: string): string {
  if (existing === null) return newContent;
  let base: Record<string, unknown> = {};
  try {
    const parsed: unknown = JSON.parse(existing);
    if (parsed !== null && typeof parsed === 'object' && !Array.isArray(parsed)) {
      base = parsed as Record<string, unknown>;
    }
  } catch {
    return newContent;
  }
  let incoming: Record<string, unknown> = {};
  try {
    const parsed: unknown = JSON.parse(newContent);
    if (parsed !== null && typeof parsed === 'object' && !Array.isArray(parsed)) {
      incoming = parsed as Record<string, unknown>;
    }
  } catch {
    return existing;
  }
  return JSON.stringify({ ...base, ...incoming }, null, 2);
}
