/**
 * openhands-specific lint hooks. Each one names exactly what is dropped:
 *   - permissions: every allow/deny/ask entry (there is no permissions file).
 *   - hooks: unsupported events, entries that map to no handler, and the fact
 *     that a project `hooks.json` completely suppresses the global one.
 *   - mcp: remote servers the shared plugin `.mcp.json` cannot carry.
 *   - agents: canonical fields outside `KNOWN_FIELDS`, and the agent-level
 *     `hooks:` key, which is the one that can cost the user the whole agent.
 */

import { AB_HOOKS, AB_PERMISSIONS } from '../../core/canonical-paths.js';
import type { CanonicalAgent, CanonicalFiles, LintDiagnostic } from '../../core/types.js';
import { createWarning, unsupportedHookEventNames } from '../../core/lint/shared/helpers.js';
import { hasAgentValue } from '../antigravity/agents-format.js';
import {
  OPENHANDS_HOOK_EVENTS,
  droppedHookEntryEvents,
  openhandsHookEventField,
} from './hooks-format.js';
import {
  OPENHANDS_TARGET,
  OPENHANDS_AGENTS_DIR,
  OPENHANDS_HOOKS_FILE,
  OPENHANDS_MCP_FILE,
} from './constants.js';

const CANONICAL_MCP = '.agentsmesh/mcp.json';

/**
 * Canonical agent fields OpenHands never applies. `permissionMode`, `maxTurns`
 * and `mcpServers` have real OpenHands counterparts (`permission_mode`,
 * `max_iteration_per_run`, `mcp_config`) but agentsmesh writes the canonical
 * camelCase key, because the file is shared byte for byte with antigravity.
 */
const OPENHANDS_INERT_AGENT_FIELDS: readonly (keyof CanonicalAgent)[] = [
  'disallowedTools',
  'maxTurns',
  'mcpServers',
  'memory',
  'permissionMode',
];

export function lintPermissions(canonical: CanonicalFiles): LintDiagnostic[] {
  const permissions = canonical.permissions;
  if (!permissions) return [];
  const entries = [...permissions.allow, ...permissions.deny, ...(permissions.ask ?? [])];
  if (entries.length === 0) return [];

  return [
    createWarning(
      AB_PERMISSIONS,
      OPENHANDS_TARGET,
      `OpenHands has no allow/deny/ask permission file. Its only permission surface is the ` +
        `per-agent permission_mode (always_confirm, never_confirm, confirm_risky) in ` +
        `${OPENHANDS_AGENTS_DIR}/<name>.md, which is a confirmation policy for one subagent and ` +
        `cannot express tool or path patterns. All ${entries.length} entr(ies) are dropped: ` +
        `${entries.join(', ')}.`,
    ),
  ];
}

export function lintHooks(canonical: CanonicalFiles): LintDiagnostic[] {
  const hooks = canonical.hooks;
  if (!hooks || Object.keys(hooks).length === 0) return [];
  const diagnostics: LintDiagnostic[] = [];

  const unsupported = unsupportedHookEventNames(hooks, OPENHANDS_HOOK_EVENTS);
  if (unsupported.length > 0) {
    diagnostics.push(
      createWarning(
        AB_HOOKS,
        OPENHANDS_TARGET,
        `HookConfig forbids unrecognised keys, so ${unsupported.join(', ')} cannot be written ` +
          `and is dropped; ${OPENHANDS_HOOK_EVENTS.join(', ')} are the only events projected.`,
      ),
    );
  }

  const dropped = droppedHookEntryEvents(hooks);
  if (dropped.length > 0) {
    diagnostics.push(
      createWarning(
        AB_HOOKS,
        OPENHANDS_TARGET,
        `${dropped.join(', ')} carries an entry with neither a command nor a prompt, which ` +
          `HookDefinition rejects, so those entries are dropped.`,
      ),
    );
  }

  diagnostics.push(
    createWarning(
      AB_HOOKS,
      OPENHANDS_TARGET,
      `Hook discovery takes the first ${OPENHANDS_HOOKS_FILE} it finds and does not merge: a ` +
        `project file completely suppresses the one generated by \`agentsmesh generate ` +
        `--global\`. Keep the events you need in both, or generate at one scope only.`,
    ),
  );

  return diagnostics;
}

export function lintMcp(canonical: CanonicalFiles): LintDiagnostic[] {
  const servers = canonical.mcp?.mcpServers;
  if (!servers) return [];
  const remote = Object.entries(servers)
    .filter(([, server]) => !('command' in server))
    .map(([name]) => name);
  if (remote.length === 0) return [];

  return [
    createWarning(
      CANONICAL_MCP,
      OPENHANDS_TARGET,
      `${OPENHANDS_MCP_FILE} is the shared Open Plugin Specification file, whose server model ` +
        `requires \`command\`; one remote entry stops every server in it loading. ` +
        `${remote.join(', ')} are dropped.`,
    ),
  ];
}

/** Events `HookConfig` raises on, which makes the loader skip the whole file. */
function fatalAgentHookEvents(agent: CanonicalAgent): string[] {
  return Object.keys(agent.hooks).filter((event) => openhandsHookEventField(event) === null);
}

function lintAgentFields(agent: CanonicalAgent): LintDiagnostic[] {
  const inert = OPENHANDS_INERT_AGENT_FIELDS.filter((field) => hasAgentValue(agent, field));
  const carriesHooks = Object.keys(agent.hooks).length > 0;
  if (inert.length === 0 && !carriesHooks) return [];

  const named = carriesHooks ? [...inert, 'hooks'].sort() : [...inert];
  return [
    createWarning(
      agent.source,
      OPENHANDS_TARGET,
      `${OPENHANDS_AGENTS_DIR}/${agent.name}.md is shared byte for byte with Antigravity, so ` +
        `agentsmesh writes canonical ${named.join(', ')} there verbatim. OpenHands reads name, ` +
        `description, model, color, tools, skills, permission_mode, max_iteration_per_run, ` +
        `max_budget_per_run, mcp_config, profile_store_dir, condenser and hooks, so those keys ` +
        `land in AgentDefinition.metadata and are never applied` +
        (carriesHooks
          ? `; hooks is parsed but a canonical entry is not a HookMatcher, so no hook runs.`
          : `.`),
    ),
  ];
}

/**
 * Wired as `generators.lint`, the only per-target lint hook that is not gated on
 * the `rules` feature, so it fires for a feature set that enables `agents` alone.
 * Best-effort events are NOT excluded here: an unknown key in an agent's `hooks:`
 * costs the user the entire agent, not one recall refinement.
 */
export function lintAgents(canonical: CanonicalFiles): LintDiagnostic[] {
  const diagnostics: LintDiagnostic[] = [];
  for (const agent of canonical.agents) {
    diagnostics.push(...lintAgentFields(agent));
    const fatal = fatalAgentHookEvents(agent);
    if (fatal.length === 0) continue;
    diagnostics.push(
      createWarning(
        agent.source,
        OPENHANDS_TARGET,
        `HookConfig raises "Unknown event type" for ${fatal.join(', ')}, and ` +
          `load_agents_from_dir swallows the error and skips the whole agent: OpenHands would ` +
          `not load ${OPENHANDS_AGENTS_DIR}/${agent.name}.md at all. Remove those events from ` +
          `the agent, or move them to .agentsmesh/hooks.yaml.`,
      ),
    );
  }
  return diagnostics;
}
